### ISSUE TITLE
convertGDP with multiple spatial sub-dimensions

### ISSUE THREAD

**Issue by caviddhen** [pik-piam/GDPuc#22]
With multiple spatial sub-dimensions, GDPuc does not work correctly.

here, the proposal would be to change 

[L23 of utils()](https://github.com/pik-piam/GDPuc/blob/23c81287d97820f774853580f9f95762c823694c/R/utils.R#L23) to use magclass::as.data.frame(rev = 2), and, when there are 2 spatial dimensions, convertGDP() would require an additional parameter knowing which regional dimension to use. 

Use case is bilateral trade margins, with dim1.1 being exporting country and dim 1.2 being the importing country, and the value based on the exporting region.

Will try to do a PR as a proposal with time.

**Comment by johanneskoch94** [comment]
Thanks for reporting this!
We can definitely start by using the [`magclass::as_tibble()`](https://github.com/pik-piam/magclass/blob/master/R/as_tibble.R) method. Something like this https://github.com/johanneskoch94/GDPuc/commit/826ebbebfc439aef5c02f4a3503319231510e3b2. 

We could then create an argument for the magpie column name, or we could warn the user to convert to tibble beforehand. Something like: 
`my_magpie |> as_tibble() |> rename("iso3c" = "region1") |> convertGDP() |> as_magpie()`

Do you have a strong preference?
