### ISSUE TITLE
convertGDP(replace_NAs) does not work as intended/documented

### ISSUE THREAD

**Issue by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [pik-piam/GDPuc#36]
I am puzzled by `convertGDP(replace_NAs)`.  It appears that `convertGD(…, replace_NAs = "with_USA")` is the default mode, at least within the `mrremind` package:
```
$ grep convertGDP\( ./R/*.R | wc -l
21
$ grep replace_NAs ./R/*.R | wc -l
20
```
But it does not opperate as advertised
> ```
> "with_USA": missing conversion factors in the source object are replaced with
> the conversion factors of the USA.
> ```
instead converting all values with the USA factors
```
toolGetMapping('regionmappingH12.csv') %>% 
  as_tibble() %>% 
  select(iso3c = CountryCode) %>% 
  mutate(value = 1) %>% 
  convertGDP(unit_in  = 'constant 2005 US$MER',
             unit_out = 'constant 2017 US$MER',
             replace_NAs = 'with_USA') %>% 
  rename(convertGDP_with_replace = 'value') %>%
  mutate(value = 1) %>% 
  convertGDP(unit_in  = 'constant 2005 US$MER',
             unit_out = 'constant 2017 US$MER') %>% 
  rename(convertGDP_without_replace = 'value') %>% 
  arrange(convertGDP_with_replace != convertGDP_without_replace)
# # A tibble: 249 × 3
#    iso3c convertGDP_with_replace convertGDP_without_replace
#    <chr>                   <dbl>                      <dbl>
#  1 USA                      1.23                       1.23
#  2 ABW                      1.23                       1.24
#  3 AFG                      1.23                       1.34
#  4 AGO                      1.23                       1.10
#  5 ALB                      1.23                       1.07
#  6 AND                      1.23                       1.03
#  7 ARE                      1.23                       1.43
#  8 ARG                      1.23                       2.35
#  9 ARM                      1.23                       1.46
# 10 ASM                      1.23                       1.50
# # ℹ 239 more rows
# # ℹ Use `print(n = ...)` to see more rows
# Warning message:
# NAs have been generated for countries lacking conversion factors! 
```
Clarification is very much appreciated.

**Comment by johanneskoch94** [comment]
Oh my... I apologize for this, and thanks for raising the issue. This looks very bad, but I'm 80% certain, that the calculation is actually what is intended. So the documentation is wrong (and the actual implementation also completely misleading). I will check this with @fbenke-pik to be certain, and work on a fix straight away.

(It stems from a sloppy implementation of "with_USA" (related to #30), and the argument "use_USA_deflator_fall_all"...)

**Edit**: actually, I think this is very bad, and not what was intended. The default used to be `replace_NAs = "linear"`, or some combination, such as `replace_NAs = c("linear", "no_conversion")`. Then the option "with_USA" was introduced, to be used in combination with `"linear"`,` c("linear", "with_USA")`. But then @fbenke-pik found #30, and after checking with me (and me not realizing there was a bug), switched to using only `"with_USA"`. So I assume, that you, @fbenke-pik, initially wanted to use `c("linear", "with_USA")`, so not overwrite all conversion factors with the US ones, but only missing ones, right?

**Comment by fbenke-pik** [comment]
This is not what I intended, I was expecting to only use USA conversion factors in cases where no country-specific conversion factor was found.

Johannes, can you provide a quick bugfix, or should we switch to another fallback option in `replace_NAs`?

**Comment by fbenke-pik** [comment]
Thanks for spotting this, Michaja!

**Comment by 0UmfHxcvx5J7JoaOhFSs5mncnisTJJ6q** [comment]
I am going to miss the _"is chemicals production in 2070 in Uzbekistan 1.23 times of what it used to be"_ metric while debugging :cry:
